defmodule Tackle.Lib.Cancellation.Store do
  @moduledoc """
  Behaviour for cancellation signal storage.

  Tackle.Lib's cancellation API is intentionally small, but cancellation state must
  be visible across the host process, the loop, LLM adapters, and tools. Hosts
  that do not want Tackle.Lib's default storage can provide their own module by
  implementing this behaviour and configuring it with `:cancellation_store`:

      config :tackle_lib, cancellation_store: MyApp.TackleCancellationStore

  In-tree hosts can also configure the same option under their application key:

      config :my_app, Tackle.Lib,
        cancellation_store: MyApp.TackleCancellationStore

  Stores receive an opaque signal id generated by `Tackle.Lib.Cancellation` and are
  responsible for preserving cancelled reasons until `delete/1` is called.
  """

  @type signal_id :: reference()
  @type reason :: term()

  @callback cancel(signal_id(), reason()) :: :ok
  @callback reason(signal_id()) :: reason() | nil
  @callback delete(signal_id()) :: :ok
end
