defmodule Tackle.Lib.Tool.Call do
  @moduledoc """
  Normalized tool invocation requested by an LLM.

  `id` is the provider/tool-call id when one exists, otherwise generated by the
  loop. `definition_id` is optional stale-call protection metadata: if a model
  echoes an older tool definition id, `Tackle.Lib.Tool.Registry.resolve/2` rejects
  the call instead of dispatching to a changed tool.
  """

  @type t :: %__MODULE__{
          id: String.t() | nil,
          name: String.t(),
          arguments: map(),
          definition_id: String.t() | nil,
          raw: term()
        }

  defstruct [:id, :name, arguments: %{}, definition_id: nil, raw: nil]
end
